### ISSUE TITLE
Renders weirdly on FF 38.0.5

### ISSUE THREAD

**Issue by ktham** [interhigh/interhigh.github.io#10]
As of 352a1bc0f6033039fd1b560899ece38f4a6e6001
Chrome 44 on OS X renders the homepage fine, but FF 38.0.5 on OS X renders the homepage weirdly.

**Comment by tn-** [comment]
Looks like this was actually broken in 4c809feb5b22839349e82900b2fafbdeeb110acd, will send out a fix soon.

**Comment by tn-** [comment]
Should be fixed in latest.
